import Head from "next/head";
import Portrait from "../components/Portrait/Portrait";
import Nav from "../components/Nav/Nav";

import s from "../styles/index.module.scss";
import Promos from "../components/Promos/Promos";
import Menu from "../components/Menu/Menu";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Donuts Homer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Nav />
        <div className={s.portrait}>
          <Portrait />
        </div>
        <div className={s.promos}>
          <Promos />
          <Menu />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
