// import prisma from "../lib/prisma";
import { useEffect, useRef, useState } from "react";
import Head from "next/head";

//COMPONENTS
import Portrait from "../components/Portrait/Portrait";
import Nav from "../components/Nav/Nav";
import Menu from "../components/Menu/Menu";
import Promos from "../components/Promos/Promos";
import Local from "../components/Local/Local";
import Footer from "../components/Footer/Footer";
import WsButton from "../components/WsButton/WsButton";

import s from "../styles/index.module.scss";

export default function Home({ feed }) {
  const menuDivRef = useRef(null);
  const promosDivRef = useRef(null);
  const localDivRef = useRef(null);

  const [scrollY, setScrollY] = useState(0);

  // useEffect(() => {
  //   window.onscroll = function (e) {
  //     setScrollY(window.scrollY); // Value of scroll Y in px
  //   };
  // }, []);


  return (
    <div>
      <Head>
        <title>Donuts Homero</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={s.main}>
        <Nav menuDivRef={menuDivRef} localDivRef={localDivRef} />
        <div className={s.portrait}>
          <Portrait />
        </div>
        <div className={s.promos}>
          <Promos promosDivRef={promosDivRef} />
          <Menu menuDivRef={menuDivRef} />
          <Local localDivRef={localDivRef} />
        </div>
        <WsButton scrollY={scrollY} />
        <Footer menuDivRef={menuDivRef} promosDivRef={promosDivRef} />
      </main>

      <footer></footer>
    </div>
  );
}

// export const getStaticProps = async () => {
  // const feed = await prisma.post.findMany({
  //   where: { published: true },
  //   include: {
  //     author: {
  //       select: { name: true },
  //     },
  //   },
  // });
  // return { props: { feed:[] } };
// };
